### ISSUE TITLE
Support files: questions and recommended clarifications

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#159] opened 2024-05-28 14:47 UTC
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/e1c338e9-b883-4f9a-8a9f-8bf71248bb72)

1. Make a clear distinction throughout the PS and DCEG between support files referenced from a dataset and those intended for other purposes.
    * Support file
      * general term for all support files
    * ENC (dataset) support file
      * classic S-57 support file
      * referenced from a feature via the `fileReference` attribute
    * System support file
      *  ISO metadata, language packs, etc.
      * never referenced from a feature via the `fileReference` attribute

2. Recommend that S-101 restrict the character encoding of all ENC support files (regardless of format) to UTF-8.
    * DCEG restricts character encoding of TXT files to UTF-8, restriction should also be noted in PS.
    * S100_SupportFileDiscoveryMetadata supports other encodings via defaultLocale
      * this complicates support file management by allowing multiple encodings of the same support file.
        * It's unclear how these alternate character encodings are supposed to be associated with one another.

3. Recommend using unambiguous terminology rather than "printable characters".
    *  Suggest referencing UTF-8 values/ranges: https://www.fileformat.info/info/charset/UTF-8/list.htm

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/bf6cf79c-77d1-4e5d-9789-b49e272cabcc)

4. Recommend that DCEG restricts ENC support files to TXT format.
    * What is the use case for XML referenced from a dataset feature?
      * Recommend that XML is only used for system support files, XML support files should not be referenced via `fileReference`.
    * What is the use case for HTML referenced from a dataset feature?
      * If allowed, clarify how to ensure that night vision is not impacted by display of HTML.
    * What is the use case for an HTML system support file?
    * Recommend disallow ENC support files in HTML format.

**Comment by MikusRL** [comment] 2024-05-29 07:38
These are some other Support File TG members comments regarding the Support file management clarifications in the documentations so far:

Raphael M.:

> "...
> My provisional proposal for S-101:
> - Restrict the allowed values of S100_ResourcePurpose in S-101 to supportFile (traditional support files referenced from feature or information types) & languagePack.
> - I don't think S-101 needs GMLSchema, & ISOMetadata should be prohibited as advised by the S-100 WG.
> - The only use cases I can think of for "other" are styles or scripts used by traditional support files, and codelists for languages, etc.
> - My understanding of current thinking is that updates to portrayal and alert catalogues will be handled outside of the S-101 exchange sets., i.e., an S-101 exchange set will contain either an entire PC or no PC. .... Either will simplify support file management.
> ..."

Jonathan P.:

> "...
>  I wanted to express my support for Raphael's comments. I'm not sure modifications to S-100 Part 17 are possible now, nor justified - whilst the current Part 17 has some idiosyncrasies the basic idea of associating one resource with another through a relationship in the CATALOG.XML is a sound concept. The uniqueness of resource names is now also a part of S-100 so these should be able to be used and test data constructed for each test case. 
> 
> I would agree with Raphael's comment on S-101, all of which seem sound to me. 
> 
> The main task we have is constructing good test scenarios for S-164 which involve supporting resources and I would agree that the basic categorisation you've identified between **dataset** support files and **other** supporting resources is a good way to partition those tests. We already have tests for e.g. catalogues and language packs but our tests for support files need expansion I believe, specifically:
> - install, update, modification and deletion of support files either directly (in the dataset) or through the catalogue (both I think are acceptable as far as S-100 is concerned)
> - shared resources in an exchange set, also when updating breaks the "sharing" between two datasets to ensure the ECDIS can sensibly resolve any ambiguities.
> - datasets which use previously installed shared resources? One we should consider in our scenarios.
> - each of the different file types need testing in these contexts as well.
> - I'm just finishing off the latest draft of S-98 Annex C and I think the question of HTML/XML and its rendering in the ECDIS is still to be resolved, although we have had some productive discussions so far. Each filetype requires a test.
> 
> If we can work on these scenarios and develop any guidance required which can usefully be inserted into S-98 Annex C that would be a good use for the group.
> ..."

I myself support David G. recommendations, that the "_**Support files**_" term should be used in general when describing ALL S-100 Support files, and divide further down by dividing first in two categories - _**Dataset Support files**_, and _**System Support files**_. This will ease the implementation interpretation of the two different Support files the S-100 has. This aligns also with Jonathan's comment. 
We can start to use this approach in the S-101 Main and DCEG documents, and further use similar definitions and appropriate descriptions under those also in the S-98. Of course it would be ideal if it initially gets its way also in the S-100 for the other S-100 Product Specifications to use the same terminology, but for now it could stay as a "backlog" for its next edition, as everyone here explains. I also trust that the Davids recommendation above does not "break" the current S-100 v.5.2 texts. It just standardizes and explains one step further on the highest level the two Support files concepts for all PSes to use/describe these in the same way without ambiguity whichever is needed or forbidden for a particular PS as needed.

With the above in mind then it is possible to describe in the S-101 how the two Support file types is intended to be working for the S-101 and ECDIS -what is allowed, what is prohibited, what goes under which of the two above, and is there a need to restrict and describe any of the two further in the S-101 or can it just be applied as intended and allowed in full under the S-100.

**Comment by MikusRL** [comment] 2024-05-29 09:46
Just to clarify - under the Dataset Support file meant is the Product Dataset Support file (or simply ENC Support file). 

There can be a Support file to a System Support file, but that should be assumed to be a System Support file to a System Support file. A System Support file is not a Dataset in terms of the S-100. I hope we all agree to this regarding the Support files.

**Comment by rmalyankar** [comment] 2024-06-03 08:17
S-100 Part 17 Table PT_Locale states "UTF-8 is used in S-100".

> What is the use case for HTML referenced from a dataset feature?

Notices to mariners, including T & P notices. Schedules. Restrictions where different restrictions apply to different classes of vessels. Any structured format. Anything that needs to include an inline image, like signal lights.

> What is the use case for XML referenced from a dataset feature?

Notices to mariners and navigation warnings when they are distributed in XML format.


What is the use case for specifically **text** files referenced from a dataset feature? ('That's what we have been using so far' is not a use case.)

**Comment by MikusRL** [comment] 2024-06-03 11:52
Thank you for input @rmalyankar . Very valuable. Have the above been in the back of the heads when drafting the PS Support files texts already? We for example struggle to pull the above clarity out of the texts and tables currently in the PS on Support files. 

And we think that by defining that "vague" concept (or next granularity down if you will) of "Dataset support files" and "System support files" would help us all to better describe what you clarified above in the comment for example. At the moment it is possible to assign anything to anything, and it is a lot of "assuming" that it is how it is supposed to be or could work..., which is too broad to be implemented to support. If the proposed or similar division is introduced when describing the support files at any time, then it becomes possible to describe also the differences of the HTML for a dataset and for a system. Now if one would want to describe or restrict two different formatting needs for the dataset support file and system support file for the same support file format or resource purpose, then it is done with a potential for miss-implementation or miss-production.

Also I still would like to point out that the TIFF only vs TIFF+JPEG decision for picture files is for the backward compatibility for Dual Fuel period. I don't see why the same point is not in the same strength applied also for the textual files during the Dual Fuel period. I even think that it would have been easier to convert without an ambiguity a JPEG file to a TIFF file automatically, than a fully formatted HTML files that includes tables and images back to a simple TXT file (+ appropriate TIFFs?) for the S-57 counterpart Dual Fuel ENCs. Speaking of "Images" in the HTML files as you describe above, is that allowed? I am not an expert in HTML with images, but are these intended to be a Support file to a Support file or are these all inbuilt in the Base64 form? If it is a support file to a support file, what kind of Support file it is expected to be? "System" or still a "Dataset" support file? Does it mean that it then can be only TIFF as described by S-101PS and DCEG? 

These all are long descriptions of the uncertainty that there is with the new way of the Support files in general throughout the Standard and the Product Specifications. All these can be easily described as @rmalyankar proposed above, but only if we have one more granularity for describing them to what the Support file described applies to. And not necessarily there has to be a literal (physical) division in the model as such as well.

**Comment by MikusRL** [comment] 2024-06-03 16:51
In the 03.06.2024 VTC call (@DavidGrant-NIWC , @rmalyankar , @skjeves, Su Marks , @kusala9, @MikusRL ) 

- [ ]  It was agreed on the principle to divide the Support files into two distinct types for Support files for purposes of clearer description in the Product Specification:

> ... the "_**Support files**_" term should be used in general when describing ALL S-100 Support files, and divide further down by dividing first in two categories - _**Dataset Support files**_, and _**System Support files**_. ...

- [ ]  It was also agreed that the combination "_**Dataset Support file**_" would be used once and further referred to as an "_**ENC Support file**_" further throughout the PS and the DCEG.

- [ ]  It was agreed that @MikusRL would generate the redline proposal texts for the S-101 PS and DCEG taking as a baseline the clean versions of the v.1.3 documents of the PS and the DCEG, and upload the redlines in this issue.

- [ ]  It was agreed which S100_ResourcePurpose and S100_SupportFileFormat is assumed to be which type of the Support file - "ENC" or "System", and agreed on adding appropriate comments to the Remarks fields of tables 12.1.3.1 and 12.1.3.4.

- [ ]  It was agreed to propose taking out the HTM and XML file formats as allowable for the ENC Support file text formats from the PS and DCEG descriptions, and relevant Remarks comment added in the table 12.1.3.1 that XML is for System Support files only and HTM is irrelevant for the S-101 PS at this stage.

- [ ]  It was agreed to add to the Remarks field of JPEG2000 format and ISO Metadata and GML Schema that these are not relevant for the S-101 Product Specification 

- [ ]  File less data management was discussed in regards to the Support files, and it was agreed that it will be brought up by @kusala9 at the PT meeting. 

- [ ]  It was agreed that @kusala9 , @rmalyankar and @skeves will bring the HTML as a Dataset Support file format issue to the NIPWG for further discussion

- [ ]  It was agreed that the S-100 maintenance proposal would be considered to be created for aligning the used Support file conceptual division for clearer text description purposes for use also at the S-100 level. This proposal would not imply any data model or schema changes requirements.

**Comment by rmalyankar** [comment] 2024-06-10 05:15
Haven't heard/seen anything more since, am assuming redlines mentioned above are still being prepared and will be uploaded for review/comment.

**Comment by MikusRL** [comment] 2024-06-10 08:19
Proposed Redlines attached. 
The Main S-101 PS document:
[S-101 ENC_Product_Specification_Clean.docx](https://github.com/user-attachments/files/15758972/S-101.ENC_Product_Specification_Clean.docx)

The S-101 DCEG (a bit later will be uploaded):

**Comment by MikusRL** [comment] 2024-06-10 16:27
Here will be attached the finalized redline changes documents as agreed and approved by the S-101PT13 meeting. 
The main S-101 PS document:

The S-101 DCEG:

**Comment by MikusRL** [comment] 2024-07-16 14:16
"Support files" agreed terms further should be updates in S-98 accordingly discussed in this issue: https://github.com/iho-ohi/98-interoperability/issues/49, and ECDIS checks are considered under this issue: https://github.com/iho-ohi/S-164-Sub-Group/issues/87

This issue can now be closed as completed, thanks @JeffWootton

**Comment by JeffWootton** [comment] 2024-07-24 09:26
All issues raised above have been addressed and Actions applied for S-101 Edition 1.4.0 (refer to Decisions and Actions from S-101PT13).

Close Issue.

**Closed by JeffWootton** 2024-07-24 09:26 UTC
Labels: Product Specification, DCEG, For S-101 Ed 2.0.0
