### ISSUE TITLE
Overlapping scale ranges

### ISSUE THREAD

**Issue by Christian-Shom** [iho-ohi/S-101-Documentation-and-FC#52] opened 2022-10-13 09:17 UTC
**S-101 PS 1.1.0 draft review (clauses 4.5.3): UKHO suggests prohibiting scale ranges overlap:**
"_Data Coverage features from different datasets covering the same geographical area, **must have non overlapping, continuous Display Scale Ranges** (see fig 4.7)._"

**Comment by Christian-Shom** [comment] 2022-10-13 10:06
Although figure 4.7 (figures in the former version were showing ovelapping ranges) suggests that there is no scale ranges overlap between data coverages at a same geographic position, this is not written anywhere in S-101 documentation.
Yet, I think this is a question that is worth asking. 

- **Does it make any sense having scale range overlapping in an ENC portfolio?**
This would mean that, at certain display scales, 2 datasets could be displayed (even if the loading/display rules will drive the ECDIS to choose only one of them).

- **Are there use cases where a scale range overlap would be needed?** If not, why allowing scale range overlap in the PS?

I do not see such use cases and am of the opinion of prohibiting scale range overlap as proposed by the UKHO, for edition 1.1.0.

**Comment by Christian-Shom** [comment] 2022-10-20 15:09
Sub-Group meeting 2022-10-19 agreed on prohibiting scale ranges overlap on a same geographical area.

**Comment by JeffWootton** [comment] 2023-08-08 10:45
Refer to comment for Issue #19:

Agree that the last response from @alvarosanuy needs to be discussed and resolved in the Main document, as this scenario is not currently covered. As I see it, there are two solutions:

1) Set minimumDisplayScale for the larger scale dataset to the largest maximumDisplayScale of any overlapping smaller scale datasets. The ECDIS would then need to apply the convention specified in clause 4.6, 3rd paragraph, of the S-101 Main document (Ed. 1.1.0) - "When the mariner’s selected viewing scale (MSVS) is smaller than the value indicated by minimum display scale, features within the Data Coverage feature are not displayed, except where the System Database does not contain a dataset covering the area at a smaller scale, in which case the dataset will be continuously displayed.".
2) Set minimumDisplayScale for the larger scale dataset to the smallest maximumDisplayScale of any overlapping smaller scale datasets. This however would break the rule at clause 4.6, 2nd paragraph, of the S-101 Main document (Ed. 1.1.0) - "There must not be overlapping scale ranges between datasets covering the same geographical area.". Tis would then need to be included as an additional "exception" along with the "5 metre overlap" exception.

It appears that, following the decision of the Sub-Group, only option (1) above is applicable. Corresponding guidance therefore needs to be developed for the S-101 Main document.

To be discussed at next DCEG Sub-Group meeting, for submission to S-101PT11.

**Comment by DavidGrant-NIWC** [comment] 2023-08-09 19:06
_"features **within the Data Coverage** feature are not displayed,"_

This wording is misleading. Datasets should always be loaded and displayed in their entirety. In any case, the data coverage features all must share a common minimum display scale (see clause 4.5.3 bullet 3a) so it's impossible for features within a particular `dataCoverage` to independently turn off when zooming out. Also note that the features/dataset may remain on if the dataset is being used to "fill-in" what would otherwise be empty areas of the display.

IMO, 4.6 paragraph three and four should be removed. The loading / display requirements are already specified in clause 4.7 / Annex D, and the overscale indication / pattern requirements are duplicated in S-98 Annex C.

**Comment by TDYCARHugh** [comment] 2023-08-09 20:14
@DavidGrant-NIWC re: " so it's impossible for features within a particular dataCoverage to independently turn off when zooming out."

I am confused by this statement. It should be possible to have features turn off while zooming out if the feature has a scaleMinimum that indicates it should no longer be visible at the current display scale. I think the intent is that the data coverage would cover the range of scales the data is intended for without forcing every feature within a dataCoverage to have the same scaleMinimum.

**Comment by DavidGrant-NIWC** [comment] 2023-08-09 22:01
> @DavidGrant-NIWC re: " so it's impossible for features within a particular dataCoverage to independently turn off when zooming out."
I am confused by this statement.

I worded that poorly. The issue is complicated; the feature can have a `scaleMinimum`, the spatial associated with the feature can have a `scaleMinimum`, and each `DataCoverage` can have a `scaleMinimum`.

>  I think the intent is that the data coverage would cover the range of scales the data is intended for without forcing every feature within a dataCoverage to have the same scaleMinimum.

It can't be used for that purpose because it's being used to control the data loading algorithm and serving as a proxy for navigational purpose.

>   I think the intent is that the data coverage would cover the range of scales the data is intended for without forcing every feature within a dataCoverage to have the same scaleMinimum.

Yes, the display of individual features may change based on the MSVS and any `scaleMinimum` attribute on each individual feature or spatial. However, `scaleMinimum` on the `DataCoverage` features can only toggle the display of every feature within the dataset, it can't affect some subset of the features constrained to the area of a particular `DataCoverage`. This is because all the `DataCoverages` within a dataset must share a common value for the `minimumDisplayScale` attribute. Zooming out past that `minimumDisplayScale` value will (in most circumstances) cause the entire dataset to unload.

Also, note that there is no direct relationship between a given feature and a `DataCoverage`. The `DataCoverage` has an associated geometry, and the feature has an associated geometry (theoretically it could have multiple geometries). These geometries have no direct relationship, and there are no feature associations to associate a feature with a `DataCoverage`.  There is no description (that I can find) of any formal spatial relationship.
* The DCEG requires: _"When a feature extends across datasets of overlapping scale ranges, its geometry must be split at the 
boundaries of the Data Coverage features and its complete attribute description must be repeated in each dataset."_.
    * The DCEG doesn't specify (as far as I can tell) whether geometries **within** a dataset must be split at the boundaries of each `DataCoverage`.
* Visibility on the screen is determined by the geometries used in the drawing instructions which depict the feature, which do not necessarily match the geometry associated with the feature.
    * Leg lines and sector arcs on lights are not even constrained to the dataset boundary.

**Comment by TDYCARHugh** [comment] 2023-08-10 16:54
Thanks for the clarification David.  I agree.
Scales in a _DataCoverage_ and scales in features are for different purposes, no need to align/restrict.
Seems sensible to split geometries of features at any _DataCoverage_  boundary.

Symbols, light sectors and text drawing beyond a  _DataCoverage_ is probably a different discussion topic on its own, perhaps under portrayal.

The discussions about having explicit associations with metadata features may also apply to  _DataCoverage_ if there is a need to determine this connection in portrayal such as to show/hide features in a  _DataCoverage_ at a certain scale. Otherwise the ECDIS would need to calculate what is within and cache or keep that information in a SENC for performance purposes.  In S-57 saving exchange/dataset space for associations that could be calculated by the ECDIS was a consideration that perhaps needs to be reconsidered.

I recall discussions that individual DataCoverages should not be unloaded or turned on/off. The entire dataset should be loaded/unloaded together otherwise it is just too complicated. Producers are not limited to 5 scales anymore so can split up ENCs according to usable scale ranges.

It would be much simpler if the min/max scale range is set on the dataset and not the DataCoverage. Just use the DataCoverage to show where there is data within the dataset.

**Comment by RichardCoyles** [comment] 2023-08-14 09:00
> Agree that the last response from @alvarosanuy needs to be discussed and resolved in the Main document, as this scenario is not currently covered. As I see it, there are two solutions:
> 
> 1. Set minimumDisplayScale for the larger scale dataset to the largest maximumDisplayScale of any overlapping smaller scale datasets. The ECDIS would then need to apply the convention specified in clause 4.6, 3rd paragraph, of the S-101 Main document (Ed. 1.1.0) - "When the mariner’s selected viewing scale (MSVS) is smaller than the value indicated by minimum display scale, features within the Data Coverage feature are not displayed, except where the System Database does not contain a dataset covering the area at a smaller scale, in which case the dataset will be continuously displayed.".
> 2. Set minimumDisplayScale for the larger scale dataset to the smallest maximumDisplayScale of any overlapping smaller scale datasets. This however would break the rule at clause 4.6, 2nd paragraph, of the S-101 Main document (Ed. 1.1.0) - "There must not be overlapping scale ranges between datasets covering the same geographical area.". Tis would then need to be included as an additional "exception" along with the "5 metre overlap" exception.
> 
To understand @alvarosanuy scenario, and @JeffWootton solutions, my diagram may contribute to discussion (or not). I feel the overlaps in position 2 would interfere with data loading, so position 1 is preferable.

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/108347351/571f7147-949a-43a8-b5c8-ca58d948b5a5)

**Comment by Christian-Shom** [comment] 2023-09-07 10:04
Sum-up for meeting 2023_09_07:

- The original issue is solved by clause 4.6: 
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/71139640/a2a01d49-7a9c-4a89-a79c-b50d049b405b)

- I wonder if the following sentence in the DCEG (clause 2.5.1) must not be deleted: 
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/71139640/a3610d40-b89b-4f74-83ef-c1a5c74b9a05)

**Comment by JeffWootton** [comment] 2023-11-08 10:11
Refer to Paper S-101PT11-06.5, related decisions and Actions S-101PT11-22 to 26. Changes applied for S-101 Edition 1.2.0 at DCEG clauses 2.5.1 and 2.5.9.

Close Issue pending further discussion on S-101PT11 Actions.

**Closed by JeffWootton** 2023-11-08 10:11 UTC
Labels: Product Specification, Scales
